/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/chair.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.02,0.02,0.02]} position = {[0.18,0.83,0.1]} rotation={[1.58, 0.0, -0.6]}>
        <mesh geometry={nodes.Cadeira_1.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Cadeira_2.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Cadeira_3.geometry} material={materials.lambert9SG} />
        <mesh geometry={nodes.Cadeira_4.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Cadeira_5.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.Cadeira_6.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Cadeira_7.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.Cadeira_8.geometry} material={materials.phong2SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/chair.glb')
