/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/table.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh  geometry={nodes.Cube.geometry} material={materials['monitor gry']} rotation={[0, 2.25, 0]} position={[1.2, 1.36, 1.01]} scale={[0.8, 0.02, 1.6]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['monitor gry']} position={[-0.92, -62.56, 0.96]} rotation={[-Math.PI, 0, 0]} scale={[0.04, 62.38, 0.03]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials['monitor gry']} position={[0.88, -62.56, 0.95]} rotation={[-Math.PI, 0, 0]} scale={[0.04, 62.38, 0.03]} />
        <mesh geometry={nodes.Cube003.geometry} material={materials['monitor gry']} position={[0.9, -62.56, -0.95]} rotation={[-Math.PI, 0, 0]} scale={[0.04, 62.38, 0.03]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials['monitor gry']} position={[-0.97, -62.56, -0.95]} rotation={[-Math.PI, 0, 0]} scale={[0.04, 62.38, 0.03]} />
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[0.06, 32.32, 0.01]} scale={[0.01, 19.03, 0.54]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[0.06, 18.94, 0.01]} rotation={[0, 0, -Math.PI]} scale={[-0.01, -19.03, -0.06]} />
        <mesh geometry={nodes.Cube007.geometry} material={materials.Material} position={[0.04, 32.32, 0.01]} scale={[0.01, 10.38, 0.2]} />
        <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[0.62, 1.88, 0]} scale={[0.17, 0.36, 0.24]} />
        <mesh geometry={nodes.Cube009.geometry} material={materials['Material.002']} position={[0.08, 1.88, 0]} scale={[0.1, 0.36, 0.15]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/table.glb')
